version: "3.7"

services:
  b2b-front:
    image: chodzi/proporcje:latest
    container_name: proporcje-calculator
    volumes:
      - "/app/node_modules"
      - ".:/app"
    restart: always

    environment:
      VIRTUAL_HOST: proporcje.grawires.pl
      LETSENCRYPT_HOST: proporcje.grawires.pl
      LETSENCRYPT_EMAIL: grawires@gmail.com

networks:
  default:
    external:
      name: nginx-proxy
