name: Deploy Angular Proporcje App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    # runs-on: self-hosted
    # runs-on: wsl

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and push Docker image
      run: |
        docker build -t chodzi/proporcje:latest .
        docker push chodzi/proporcje:latest

    - name: SSH into Server and Pull
      uses: appleboy/ssh-action@v1.1.0
      with:
        host: ${{ secrets.SERVER_SSH_HOST }}
        port: ${{ secrets.SERVER_SSH_PORT }}
        username: ${{ secrets.SERVER_SSH_USER }}
        password: ${{ secrets.SERVER_SSH_PASS }}
        script: |
          docker pull chodzi/proporcje:latest

    - name: SSH into Server and Stop
      uses: appleboy/ssh-action@v1.1.0
      with:
        host: ${{ secrets.SERVER_SSH_HOST }}
        port: ${{ secrets.SERVER_SSH_PORT }}
        username: ${{ secrets.SERVER_SSH_USER }}
        password: ${{ secrets.SERVER_SSH_PASS }}
        script: |
          docker stop proporcje || true
          docker rm proporcje || true

    - name: SSH into Server and RM
      uses: appleboy/ssh-action@v1.1.0
      with:
        host: ${{ secrets.SERVER_SSH_HOST }}
        port: ${{ secrets.SERVER_SSH_PORT }}
        username: ${{ secrets.SERVER_SSH_USER }}
        password: ${{ secrets.SERVER_SSH_PASS }}
        script: |
          docker rm proporcje || true

    - name: SSH into Server and Deploy
      uses: appleboy/ssh-action@v1.1.0
      with:
        host: ${{ secrets.SERVER_SSH_HOST }}
        port: ${{ secrets.SERVER_SSH_PORT }}
        username: ${{ secrets.SERVER_SSH_USER }}
        password: ${{ secrets.SERVER_SSH_PASS }}
        script: |
          docker run -d --restart unless-stopped --name proporcje -p 6951:80 chodzi/proporcje:latest
